name: Analyze

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [14, 14]
        language: [ 'javascript' ]
       
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ${{ matrix.node }}
    
    - name: Installling dependencies
      run: yarn install

    - name: Eslint / Code linting
      run: yarn lint:check

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1